namespace: pr-13

replicaCount: 1

image:
  repository: ghcr.io/federicomameli1/wayside-monitor
  tag: "ca8e237b57a407fe0afa65da7c957488f3bb1cdc"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8000

env:
  collector_stream: "wms:sensor-events"
  engine_stream: "wms:anomaly-events"
  anomaly_engine_model_ver: "vibration_model_v2.pkl"
  dead_letter_path: "/tmp/wms-dead-letter.jsonl"
