namespace: pr-20

replicaCount: 1

image:
  repository: ghcr.io/federicomameli1/wayside-monitor
  tag: "299a0cee1eeb10c44767f628a9f212dd282b3698"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8000

env:
  collector_stream: "wms:sensor-events"
  engine_stream: "wms:anomaly-events"
  anomaly_engine_model_ver: "vibration_model_v2.pkl"
  dead_letter_path: "/tmp/wms-dead-letter.jsonl"
