namespace: pr-10

replicaCount: 1

image:
  repository: ghcr.io/federicomameli1/wayside-monitor
  tag: "4040319e264aadb0c5f25c700e98bc08fb835696"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8000

env:
  collector_stream: "wms:sensor-events"
  engine_stream: "wms:anomaly-events"
  anomaly_engine_model_ver: "vibration_model_v2.pkl"
  dead_letter_path: "/tmp/wms-dead-letter.jsonl"
