namespace: pr-1

replicaCount: 1

image:
  repository: ghcr.io/federicomameli1/wayside-monitor
  tag: "6f2a32e1cbeb2fd6b7bee069ffda5826b1be270e"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8000

env:
  collector_stream: "wms:sensor-events"
  engine_stream: "wms:anomaly-events"
  anomaly_engine_model_ver: "vibration_model_v2.pkl"
  dead_letter_path: "/tmp/wms-dead-letter.jsonl"
