namespace: wayside-prod

replicaCount: 2

image:
  repository: ghcr.io/federicomameli1/wayside-monitor@sha256:683c31108cb8db89b82783760ca2c57033f5d3dde7ea589d44a3106389da00c6
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30082

env:
  collector_stream: "wms:sensor-events"
  engine_stream: "wms:anomaly-events"
  anomaly_engine_model_ver: "vibration_model_v2.pkl"
  dead_letter_path: "/tmp/wms-dead-letter.jsonl"
