namespace: pr-4

replicaCount: 1

image:
  repository: ghcr.io/federicomameli1/wayside-monitor
  tag: "31dc71f2c30d520ab5e8280742210ae64c6b94fb"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8000

env:
  collector_stream: "wms:sensor-events"
  engine_stream: "wms:anomaly-events"
  anomaly_engine_model_ver: "vibration_model_v2.pkl"
  dead_letter_path: "/tmp/wms-dead-letter.jsonl"
